Steady state ROM
robertsj/libdetran pull request #26
Opened 2020-07-15 14:49 UTC by Relzohery

This PR adds three main classes for the steady state ROM, namely;
    1. ROMBasis: This gets a user basis form a binary file and stores it in a dense matrix.
    2. OperatotProjection : This takes any matrix type (sparse, dense or shell) and basis and produce the reduced matrix(UTAU)
    3.  ROMSolver: This takes user input, mesh, material, and operator type and solves the eigenvalue problem of the reduced 
        system.

Each class has its unit test.

In the Solver test, I used  1D slab reactor and  tried three operators (Diffusion, EnergyDependent and EnergyIndependent). The Diffusion results seems reasonable.  For the EnergyDpendent operator, while the eigenvalues of the ROM is close to the true value, they don't match the one from the diffusion.

2020-07-15 15:00 UTC, Relzohery commented
@robertsj  I did not solve all the issues yet. Also, I can break this into three smaller PRs, if you want.

2020-07-15 15:29 UTC, robertsj commented
I'll take a peak today or tomorrow.  I've got an NRC conference call this afternoon and won't make a meeting with you.  I hope F that I can be in the office.

________________________________
From: Relzohery <notifications@github.com>
Sent: Wednesday, July 15, 2020 10:06 AM
To: robertsj/libdetran <libdetran@noreply.github.com>
Cc: Jeremy Roberts <jaroberts@ksu.edu>; Mention <mention@noreply.github.com>
Subject: Re: [robertsj/libdetran] Steady state ROM (#26)


@robertsj<https://github.com/robertsj> I did not solve all the issues yet. Also, I can break this into three smaller PRs, if you want.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/robertsj/libdetran/pull/26#issuecomment-658820741>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAH66G5Z6RAYWV4WLXEY5KTR3XAVXANCNFSM4O2TVGFQ>.

2020-09-29 18:56 UTC, robertsj requested changes
Comments.

2020-09-29 18:56 UTC, robertsj commented on src/solvers/rom/ROMSolver.hh
> +   void SetBasis();
maybe private

2020-09-29 18:56 UTC, robertsj commented on src/solvers/rom/ROMSolver.hh
> +#include "solvers/EigenvalueManager.hh"
delete

2020-09-29 18:56 UTC, robertsj commented on src/solvers/rom/ROMSolver.hh
> +  SP_vector x_rom;
define me

2020-09-29 18:56 UTC, robertsj commented on src/solvers/rom/ROMSolver.cc
> +    SP_lossoperator A (new DiffusionLossOperator(d_input, d_mat, d_mesh, false, 0.0, false, 1.0));
Should able to do 
```suggestion
    d_A  = new DiffusionLossOperator(d_input, d_mat, d_mesh, false, 0.0, false, 1.0);
```

2020-09-29 18:56 UTC, robertsj commented on src/solvers/rom/ROMSolver.hh
> +   typedef EnergyDependentEigenLHS<D>                LHS_Operator_T;
Maybe name these different so it's easier to see Ax=lambda B x etc

2020-09-29 18:56 UTC, robertsj commented on src/solvers/rom/ROMSolver.cc
> +  {
maybe try

```suggestion
  if (sol->sum() < 0)
  {
    sol->scale(-1);
  }
```

2020-09-29 18:56 UTC, robertsj commented on src/solvers/test/test_ROMSolver.cc
> + ROMBasis::GetBasis("/home/rabab/opt/detran/source/src/solvers/test/flux_basis_core0_diff", U);
:(

2020-10-13 18:22 UTC, robertsj approved these changes

2020-10-13 18:22 UTC, robertsj commented on src/solvers/rom/OperatorProjection.hh
> +	SP_matrixDense d_U;
```suggestion
	SP_matrixdense d_U;
```

2020-10-13 18:22 UTC, robertsj commented on src/solvers/rom/ROMBasis.cc
> + *  @brief RoMBasis class definition.
```suggestion
 *  @brief ROMBasis class definition.
```

2020-10-13 18:22 UTC, robertsj commented on src/solvers/rom/ROMBasis.cc
> +    U->insert(i, j, B[c]);
is this assembled after?

2020-10-13 18:22 UTC, robertsj commented on src/solvers/rom/ROMSolver.hh
> +#include "solvers/mg/DiffusionLossOperator.hh"
```suggestion
```

2020-10-16 00:21 UTC, merged